---
refresh_interval: 2 # seconds
max_price: 750 # dollars
urls:
  - https://www.costco.ca/playstation-5-pulse-3d-wireless-headset.product.100701494.html
  - https://www.bestbuy.ca/en-ca/product/playstation-5-console-online-only/14962185
  - https://www.bestbuy.ca/en-ca/product/playstation-5-dualsense-wireless-controller-white/14962193
  - https://www.newegg.com/p/N82E16868110291
  - https://www.newegg.com/p/N82E16868110292
  - https://www.newegg.com/p/N82E16868110293
  - https://www.walmart.ca/en/ip/playstation5-dualsense-wireless-controller-white/6000202196831
  - https://www.bestbuy.ca/en-ca/product/playstation-5-dualsense-wireless-controller-white/14962193
...
